### ISSUE TITLE
Do you know how to disable microcaching in gwan for golang?

### ISSUE THREAD

**Issue by hwongcom** [solisoft/solicms_old#1]
Do you know how to disable microcaching in gwan for golang? Thanks for the 4 version of solicms.

I would like to know how to disable microcaching in gwan for golang. Do you know? Your version seemed ok disabling php but not golang.

**Comment by solisoft** [comment]
Hi sorry for the delay,

soliCMS run ruby code, not PHP, but it works the same way for PHP, Go, Python, etc...

Look at https://github.com/solisoft/solicms/blob/master/init.c this is where I disable microcaching

**Comment by hwongcom** [comment]
Thanks. When is your c solicms coming up?

**Comment by solisoft** [comment]
soliCMS is a time free project ... But to be honest I don't have too much time right now !
I think I'll first create an admin part, to help people using it because it's not so easy to manipulate flat files for non developers ...

**Comment by hwongcom** [comment]
Keep up the great work!
